<section class="container profil">
  <div class="photo">
      <?php
      if(!preg_match("/^[A-Za-z]+/", $userClass->jmeno)){
          echo mb_strtoupper(substr($userClass->jmeno, 0,2));
      } else {
          echo mb_strtoupper(substr($userClass->jmeno, 0,1));
      }
      if(!preg_match("/^[A-Za-z]+/", $userClass->prijmeni)){
          echo mb_strtoupper(substr($userClass->prijmeni, 0,2));
      } else {
          echo mb_strtoupper(substr($userClass->prijmeni, 0,1));
      }
      ?>
  </div>
  <div class="info">
    <h4><?= $userClass->jmeno . ' ' . $userClass->prijmeni ?></h4>
    <h5><?= $userClass->email ?></h5>
    <p><?= $userClass->adresa ?></br><?= $userClass->mobil ?></p>

    <a href="logout.php">Odhlásit</a>
  </div>
  <div class="navigace">
      <ul>
        <a href="#" class="show-order-history"><li class="waves-light objednavky-link btn active">Objednávky</li></a>
        <a href="#!" class="edit-profile"><li class="waves-light settings-link btn">Změnit osobní údaje</li></a>
      </ul>
  </div>
    <?php
        $objednavky = $objednavkaClass->getObjednavkyByUser($userClass->id);
       // print_r($objednavky);
    ?>
  <div id="objednavky-historie" class="objednavky">
      <?php
        foreach($objednavky as $objednavka):
        $kosik = $objednavkaClass->getAllInObjednavka($objednavka['id']);
      ?>
      <div class="bunka">
        <div class="info">
          <div class="basic">
            <div class="date"><?=  date("j. n. Y",strtotime($objednavka['time_created'])) ?></div>
            <div class="adresa"><?= $objednavka['adresadoruceni'] ?></div>
          </div>
          <div class="price"> <?= $objednavka['cenacelkem'] ?> Kč</div>
        </div>
        <div class="produkt">
          <ul>
              <?php
              foreach($kosik as $item):
              ?>
                    <li><?= $item['pocet'] . 'x ' . $item['nazev'] . ' - ' . $item['cenaZaPocet'].' Kč' ?></li>
              <?php
              endforeach;
              ?>
          </ul>
        </div>
      </div>
      <?php
      endforeach;
      ?>
  </div>
  <div id="edit-profil" class="">
      <h4>Změna osobních údajů</h4>
      <div class="row">
    <form class="col s12" method="post">
      <div class="row">
        <div class="input-field col s6">
          <input name="email" id="email" type="email" class="validate" value="<?= $userClass->email ?>">
          <label for="email">Email</label>
        </div>
        <div class="input-field col s6">
          <input name="mobil" id="telefon" type="text" class="validate" value="<?= $userClass->mobil ?>">
          <label for="telefon">Telefon</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="jmeno" id="first_name" type="text" class="validate" value="<?= $userClass->jmeno ?>">
          <label for="first_name">Jméno</label>
        </div>
        <div class="input-field col s6">
          <input name="prijmeni" id="last_name" type="text" class="validate" value="<?= $userClass->prijmeni ?>">
          <label for="last_name">Příjmení</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input name="adresa" id="address" type="text" class="validate" value="<?= $userClass->adresa ?>">
          <label for="address">Adresa</label>
        </div>
      </div>
      <button name="editUser" type="submit" class="btn amber accent-3">Uložit změny</button>
    </form>
  </div>
  </div>
</section>

<script type="text/javascript">
  $('.edit-profile').click(function(){
      $('.objednavky-link ').removeClass('active');
      $('.settings-link').addClass('active');

      $( '#objednavky-historie').hide();
      $( '#edit-profil').show();

  })

  $('.show-order-history').click(function(){
      $( '#objednavky-historie').show();
      $( '#edit-profil').hide();

      $('.objednavky-link ').addClass('active');
      $('.settings-link').removeClass('active');
  })
</script>
