-- MySQL Script generated by MySQL Workbench
-- Thu Dec 28 17:02:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Bel3s
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Bel3s` ;

-- -----------------------------------------------------
-- Schema Bel3s
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bel3s` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `Bel3s` ;

-- -----------------------------------------------------
-- Table `Bel3s`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`user` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `body` INT NULL DEFAULT 0,
  `mobil` VARCHAR(45) NULL,
  `adresa` TEXT NULL,
  `registered` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Bel3s`.`login_attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`login_attempt` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`login_attempt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Bel3s`.`menuItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`menuItem` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`menuItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  `popis` TEXT NULL,
  `ingredience` TEXT NULL,
  `cena` INT NOT NULL,
  `id_sezona` INT NULL DEFAULT 0,
  `kategorie` VARCHAR(45) NULL,
  `gramaz` VARCHAR(45) NULL,
  `jidlo` TINYINT NOT NULL DEFAULT 1,
  `piti` TINYINT NOT NULL DEFAULT 0,
  `priloha` TINYINT NOT NULL DEFAULT 0,
  `alko` TINYINT NOT NULL DEFAULT 0,
  `hracka` TINYINT NOT NULL DEFAULT 0,
  `snidane` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`kategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`kategorie` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`kategorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `foto` VARCHAR(255) NULL DEFAULT 'pict/default.jpg',
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`objednavka` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`objednavka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `cenacelkem` FLOAT NULL,
  `zpusobdoruceni` VARCHAR(45) NULL,
  `adresadoruceni` TEXT NOT NULL,
  `poznamka` TEXT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objednavka_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_objednavka_user1`
  FOREIGN KEY (`user_id`)
  REFERENCES `Bel3s`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`admin` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`admin` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `Bel3s`.`stranka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`stranka` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`stranka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NULL,
  `role` VARCHAR(255) NULL,
  `datum` DATE NULL,
  `pouzito` TINYINT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`menuItem_has_objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`menuItem_has_objednavka` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`menuItem_has_objednavka` (
  `jidlo_id` INT NOT NULL,
  `objednavka_id` INT NOT NULL,
  `pocet` INT NULL DEFAULT 1,
  PRIMARY KEY (`jidlo_id`, `objednavka_id`),
  INDEX `fk_jidlo_has_objednavka1_objednavka1_idx` (`objednavka_id` ASC),
  INDEX `fk_jidlo_has_objednavka1_jidlo1_idx` (`jidlo_id` ASC),
  CONSTRAINT `fk_jidlo_has_objednavka1_jidlo1`
  FOREIGN KEY (`jidlo_id`)
  REFERENCES `Bel3s`.`menuItem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jidlo_has_objednavka1_objednavka1`
  FOREIGN KEY (`objednavka_id`)
  REFERENCES `Bel3s`.`objednavka` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`fotka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`fotka` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`fotka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL DEFAULT 'default.png',
  `path` VARCHAR(255) NOT NULL DEFAULT 'img/',
  `jidlo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fotka_jidlo1_idx` (`jidlo_id` ASC),
  CONSTRAINT `fk_fotka_jidlo1`
  FOREIGN KEY (`jidlo_id`)
  REFERENCES `Bel3s`.`menuItem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`sezona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bel3s`.`sezona` ;

CREATE TABLE IF NOT EXISTS `Bel3s`.`sezona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `od` DATE NULL,
  `do` DATE NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Bel3s`.`menuItem`
-- -----------------------------------------------------
START TRANSACTION;
USE `Bel3s`;
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Belfrites', 'ručně dělané smažené belgické hranolky osmažené v hovězím tuku a podávané v kornoutu', NULL, 49, 0, 'Příloha', '200g', 1, 0, 1, 0, 0, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Chicken strips', 'kousky kuřecího masa obalené v crispy směsi vyráběné ve stánku, osmažené a podávané v kornoutu', NULL, 69, 0, 'Stripsy', '170g', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Mr. Pork strips', 'kousky masa z vepřové panenky obalené v crispy směsi vyráběné ve stánku, osmažené a podávané v kornoutu', NULL, 79, 0, 'Stripsy', '170g', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Cheese BelBrie', 'smažené sýrové kousky z camembertu obalené v crispy směsi vyráběné ve stánku, osmažené a podávané v kornoutu', NULL, 69, 0, 'Stripsy', '170g', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Belgické masové koule', 'mletá masová směs s bylinkami ve tvaru koule dle belgické receptury připravené v páře a podávané v kornoutu', NULL, 69, 0, 'Masové koule', '150g', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Grande chicken baguette', 'plněná bageta s kuřecími stripsy, hranolkami, zeleninou a omáčkou', 'Chicken strips, Belfrites, Dip ', 79, 0, 'Bagety', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Grande pork baguette', 'plněná bageta s vepřovými stripsy, hranolkami, zeleninou a omáčkou', 'Mr. Pork strips, Belfrites, Dip ', 89, 0, 'Bagety', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Grande cheese baguette', 'plněná bageta se sýrovými kousky BelBrie, hranolkami, zeleninou a omáčkou', 'Cheese BelBrie, Belfrites, Dip ', 79, 0, 'Bagety', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Petite ham baquette', 'plněná zapečená snídaňová bageta se šunkou, sýrem, vejcem, zeleninou a dresinkem', NULL, 59, 0, 'Bagety', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Petite bacon baguette', 'plněná zapečená snídaňová bageta se slaninou, sýrem, vejcem, zeleninou a dresinkem', NULL, 59, 0, 'Bagety', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Petite cheese baguette', 'plněná zapečená snídaňová bageta se sýrem, zeleninou a dresinkem', NULL, 59, 0, 'Bagety', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Chicken tornade', 'tortilla plněná kuřecím masem připravovaným v páře, zeleninou a omáčkou', NULL, 79, 0, 'Tortilla', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Mr. Pork tornade', 'tortilla plněná vepřovou panenkou připravovanou v páře, zeleninou a omáčkou', '', 79, 0, 'Tortilla', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Belgická vafle', 'belgické vafle bez náplně', NULL, 29, 0, 'Wafle', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Belgická vafle plněná čokoládou', 'belgické vafle plněné čokoládou', NULL, 39, 0, 'Wafle', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Belgická vafle plněná čokoládou, šlehačkou a toppingem', 'belgické vafle plněné čokoládou, šlehačkou a toppingem', NULL, 49, 0, 'Wafle', '1ks ', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 1', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 2', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 3', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 4', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 5', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 6', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 7', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 8', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 9', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Dip 10', NULL, NULL, 10, 0, 'Omáčka', '33ml', 0, DEFAULT, 1, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Salát 1', NULL, NULL, 49, 0, 'Salát', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Salát 2', NULL, NULL, 49, 0, 'Salát', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Salát 3', NULL, NULL, 49, 0, 'Salát', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Salát 4', NULL, NULL, 49, 0, 'Salát', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Salát 5', NULL, NULL, 49, 0, 'Salát', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Bel3s`.`menuItem` (`id`, `nazev`, `popis`, `ingredience`, `cena`, `id_sezona`, `kategorie`, `gramaz`, `jidlo`, `piti`, `priloha`, `alko`, `hracka`, `snidane`) VALUES (DEFAULT, 'Salát 6', NULL, NULL, 49, 0, 'Salát', '1ks', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Bel3s`.`kategorie`
-- -----------------------------------------------------
START TRANSACTION;
USE `Bel3s`;
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Příloha', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Stripsy', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Masové koule', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Bagety', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Tortilla', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Wafle', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Omáčka', NULL);
INSERT INTO `Bel3s`.`kategorie` (`id`, `nazev`, `foto`) VALUES (DEFAULT, 'Salát', NULL);

COMMIT;

