-- MySQL Script generated by MySQL Workbench
-- Wed Sep 20 18:21:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Bel3s
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bel3s
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bel3s` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `Bel3s` ;

-- -----------------------------------------------------
-- Table `Bel3s`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `body` INT NULL DEFAULT 0,
  `mobil` VARCHAR(45) NULL,
  `adresa` TEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Bel3s`.`login_attempt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`login_attempt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Bel3s`.`menuItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`menuItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `popis` TEXT NULL,
  `ingredience` TEXT NULL,
  `cena` INT NOT NULL,
  `sezona` TINYINT NULL,
  `snidane` TINYINT NULL,
  `kategorie` VARCHAR(45) NULL,
  `gramaz` VARCHAR(45) NULL,
  `jidlo` TINYINT NOT NULL DEFAULT 1,
  `piti` TINYINT NOT NULL DEFAULT 0,
  `priloha` TINYINT NOT NULL DEFAULT 0,
  `alko` TINYINT NOT NULL DEFAULT 0,
  `hracka` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`kategorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`nouser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`nouser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`objednavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`objednavka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `nouser_id` INT NULL,
  `cenacelkem` FLOAT NULL,
  `zpusobdoruceni` VARCHAR(45) NULL,
  `adresadoruceni` TEXT NOT NULL,
  `poznamka` TEXT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objednavka_user1_idx` (`user_id` ASC),
  INDEX `fk_objednavka_nouser1_idx` (`nouser_id` ASC),
  CONSTRAINT `fk_objednavka_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Bel3s`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_objednavka_nouser1`
    FOREIGN KEY (`nouser_id`)
    REFERENCES `Bel3s`.`nouser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`admin` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `Bel3s`.`stranka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`stranka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NULL,
  `role` VARCHAR(255) NULL,
  `datum` DATE NULL,
  `pouzito` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`menuItem_has_objednavka1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`menuItem_has_objednavka1` (
  `jidlo_id` INT NOT NULL,
  `objednavka_id` INT NOT NULL,
  `pocet` INT NULL DEFAULT 1,
  PRIMARY KEY (`jidlo_id`, `objednavka_id`),
  INDEX `fk_jidlo_has_objednavka1_objednavka1_idx` (`objednavka_id` ASC),
  INDEX `fk_jidlo_has_objednavka1_jidlo1_idx` (`jidlo_id` ASC),
  CONSTRAINT `fk_jidlo_has_objednavka1_jidlo1`
    FOREIGN KEY (`jidlo_id`)
    REFERENCES `Bel3s`.`menuItem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jidlo_has_objednavka1_objednavka1`
    FOREIGN KEY (`objednavka_id`)
    REFERENCES `Bel3s`.`objednavka` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bel3s`.`fotka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bel3s`.`fotka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL DEFAULT 'default.jpg',
  `path` VARCHAR(255) NOT NULL DEFAULT 'img/jidlo/',
  `jidlo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fotka_jidlo1_idx` (`jidlo_id` ASC),
  CONSTRAINT `fk_fotka_jidlo1`
    FOREIGN KEY (`jidlo_id`)
    REFERENCES `Bel3s`.`menuItem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
